# Generated by Django 4.2.9 on 2024-01-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=256)),
                (
                    "company_website",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "company_facebook",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "complaint_reason",
                    models.CharField(
                        choices=[
                            ("DL", "DELAY"),
                            ("RPI", "Request Price Increase"),
                            ("OT", "Other"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "client_phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "gov",
                    models.CharField(
                        choices=[("CA", "Cairo"), ("GI", "Giza"), ("OT", "Other")],
                        max_length=10,
                    ),
                ),
                ("region", models.CharField(max_length=256)),
                ("neighborhood", models.CharField(max_length=256)),
                ("comment", models.TextField()),
            ],
        ),
    ]
