# Generated by Django 4.2.9 on 2024-01-12 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyreview",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="companyreview",
            name="complaint_reason",
            field=models.CharField(
                choices=[
                    ("DL", "تاخير في التسليم"),
                    ("RPI", "طلب زيادة السعر"),
                    ("OT", "اخري"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="companyreview",
            name="gov",
            field=models.CharField(
                choices=[("CA", "القاهرة"), ("GI", "الجيزة"), ("OT", "اخري")],
                max_length=10,
            ),
        ),
    ]
