# Generated by Django 4.2.9 on 2024-01-22 22:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_companyreview_land_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyreview",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
